version: '1'

services:
  db:
    container_name: dbflatworld
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 14881488
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "3305:8080"